// Global using directives

global using Microsoft.Extensions.Logging;
global using Microsoft.Maui.ApplicationModel;
global using Microsoft.Maui.ApplicationModel.DataTransfer;
global using Microsoft.Maui.Storage;
global using System.Diagnostics;
global using System.Globalization;
global using System.Reflection;
global using FluentValidation;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using MudBlazor;
global using MudBlazor.Services;
global using Streak.Core.Constants;
global using Streak.Core.Models.ViewModels.InputModels;
global using Streak.Ui.Constants;
global using Streak.Core.Repositories.DbContexts;
global using Streak.Core.Repositories.Implementations;
global using Streak.Core.Repositories.Interfaces;
global using Streak.Core.Services.Implementations;
global using Streak.Core.Services.Interfaces;
global using Streak.Core.Services.Validators;
global using Streak.Ui.Misc.ExtensionMethods;
global using Streak.Ui.Misc.Startup;
global using Streak.Ui.Misc.Utilities;
global using Streak.Ui.Services.Implementations;
global using Streak.Ui.Services.Interfaces;
global using Streak.Ui.Services.Models;
