name: streak-deploy-template

on:
  workflow_call:

env:
  DOTNET_VERSION_10: "10.0.x"

jobs:
  build-deploy-streak-app:
    runs-on: windows-2025-vs2026
    timeout-minutes: 10
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_10 }}
      - name: dotnet restore
        run: dotnet restore
      - name: run unit tests (core)
        run: dotnet test ./tests/Streak.Core.UnitTests/Streak.Core.UnitTests.csproj --logger trx --results-directory ./tests/Streak.Core.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: publish unit test results (core)
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Streak.Core.UnitTests
          path: ./tests/Streak.Core.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: build streak app
        run: dotnet publish ./src/Streak.Ui/Streak.Ui.csproj -c Release -o ./Publish/Streak.Ui
