name: streak-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # do not trigger on changes to documentation
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
