name: streak-deploy

on:
  push:
    branches:
      - main
    # do not trigger on changes to documentation
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:
    inputs:
      environmentName:
        type: environment
        default: test
        required: true
        description: Target environment
      runProvisioning:
        type: boolean
        default: false
        description: Run bicep template provisioning?

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    with:
      environmentName: ${{ inputs.environmentName || 'test' }}
      runProvisioning: ${{ inputs.runProvisioning || false }}
